spring.application.name=backend

spring.datasource.url=jdbc:postgresql://db.kwrjvqtikdikozmrfihy.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=petverseBypxp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:9090}

