spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://poonamtuptewar24_db_user:Petversebypxp@cluster0.fuaw60c.mongodb.net/petverse?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=petverse
server.port=9090